-- Header duyuru barı. MariaDB 10.6 geliştirme ortamıyla uyumludur.
CREATE TABLE IF NOT EXISTS announcements (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  code CHAR(36) NOT NULL,
  message_tr VARCHAR(240) NOT NULL,
  message_en VARCHAR(240) NULL,
  link_label_tr VARCHAR(80) NULL,
  link_label_en VARCHAR(80) NULL,
  link_url VARCHAR(500) NULL,
  link_underline TINYINT(1) NOT NULL DEFAULT 1,
  background_color CHAR(7) NOT NULL DEFAULT '#E5E5DC',
  text_color CHAR(7) NOT NULL DEFAULT '#17191D',
  duration_seconds TINYINT UNSIGNED NOT NULL DEFAULT 5,
  sort_order INT UNSIGNED NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  starts_at DATETIME(6) NULL,
  ends_at DATETIME(6) NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_announcements_code (code),
  KEY idx_announcements_public (is_active, starts_at, ends_at, sort_order),
  CONSTRAINT fk_announcements_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_announcements_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT chk_announcements_duration CHECK (duration_seconds BETWEEN 3 AND 60),
  CONSTRAINT chk_announcements_sort_order CHECK (sort_order <= 100000)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
