import { ArrowRight, Heart, MapPin, Package, ShieldCheck } from 'lucide-react';

function QuickAction({ icon: Icon, title, description, onClick }) {
  return <button type="button" onClick={onClick} className="group rounded-2xl border border-black/10 bg-white p-5 text-left transition-[transform,border-color,box-shadow] duration-200 hover:-translate-y-0.5 hover:border-black/20 hover:shadow-[0_12px_28px_rgba(20,25,30,0.06)]"><Icon className="size-5 text-[#1b2635]" strokeWidth={1.5} /><h2 className="mt-8 text-lg font-medium tracking-[-0.025em]">{title}</h2><p className="mt-2 max-w-xs text-sm leading-6 text-[#6d7580]">{description}</p><span className="mt-5 flex items-center gap-1 text-sm font-medium">Görüntüle <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></span></button>;
}

export default function AccountOverview({ user, account, onNavigate }) {
  const orderCount = account?.orders?.length || 0;
  const addressCount = account?.addresses?.length || 0;
  const favoriteCount = account?.favorites?.length || 0;
  return <div className="space-y-6"><section className="overflow-hidden rounded-2xl bg-[#1b2635] text-white"><div className="grid gap-8 p-6 sm:p-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-sm text-white/60">ALP Gözlük hesabın</p><h1 className="mt-3 max-w-xl text-[clamp(2rem,4vw,3.75rem)] font-normal leading-[0.98] tracking-[-0.055em]">Merhaba, {user.firstName}.</h1><p className="mt-4 max-w-md text-sm leading-6 text-white/70">Siparişlerini, teslimat adreslerini ve beğendiğin çerçeveleri tek yerden yönet.</p></div><div className="flex items-center gap-3 rounded-xl border border-white/15 bg-white/8 px-4 py-3 text-sm text-white/80"><ShieldCheck className="size-5 text-[#b9decf]" /><span>Hesabın güvenle korunuyor</span></div></div></section><section className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-black/10 bg-[#f2f3ef] p-5"><Package className="size-5" strokeWidth={1.5} /><p className="mt-7 text-3xl tracking-[-0.045em] tabular-nums">{orderCount}</p><p className="mt-1 text-sm text-[#69717b]">Son sipariş</p></div><div className="rounded-2xl border border-black/10 bg-[#f2f3ef] p-5"><MapPin className="size-5" strokeWidth={1.5} /><p className="mt-7 text-3xl tracking-[-0.045em] tabular-nums">{addressCount}</p><p className="mt-1 text-sm text-[#69717b]">Kayıtlı adres</p></div><div className="rounded-2xl border border-black/10 bg-[#f2f3ef] p-5"><Heart className="size-5" strokeWidth={1.5} /><p className="mt-7 text-3xl tracking-[-0.045em] tabular-nums">{favoriteCount}</p><p className="mt-1 text-sm text-[#69717b]">Favori çerçeve</p></div></section><section><div className="mb-3 flex items-end justify-between gap-5"><div><h2 className="text-xl tracking-[-0.03em]">Sana kolay gelsin</h2><p className="mt-1 text-sm text-[#69717b]">En sık kullanılan işlemler.</p></div></div><div className="grid gap-3 md:grid-cols-3"><QuickAction icon={Package} title="Siparişlerim" description="Teslimat ve ödeme durumunu anlık takip et." onClick={() => onNavigate('orders')} /><QuickAction icon={MapPin} title="Adreslerim" description="Teslimat adreslerini ekle ve düzenle." onClick={() => onNavigate('addresses')} /><QuickAction icon={Heart} title="Favorilerim" description="Kaydettiğin çerçevelere hızlıca dön." onClick={() => onNavigate('favorites')} /></div></section></div>;
}
