'use client';

import Image from 'next/image';
import { Heart, ShoppingBag } from 'lucide-react';
import { Link } from '@/i18n/navigation';

export default function Favorites({ favorites, locale, onRemove }) {
  return <section><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-[#69717b]">Sonra incelemek için kaydettiklerin</p><h1 className="mt-1 text-[clamp(2rem,4vw,3rem)] tracking-[-0.05em]">Favorilerim</h1></div><span className="rounded-full bg-[#f1f2ef] px-3 py-1.5 text-sm text-[#59616b]">{favorites.length} ürün</span></div>{favorites.length ? <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{favorites.map((product) => <article key={product.id} className="group overflow-hidden rounded-2xl border border-black/10 bg-white"><div className="relative aspect-[4/3] bg-[#f2f3f0]">{product.imageUrl ? <Image src={product.imageUrl} alt={product.name} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover transition-transform duration-300 group-hover:scale-[1.03]" /> : null}<button type="button" onClick={() => onRemove(product.id)} aria-label={`${product.name} favorilerden çıkar`} className="absolute right-3 top-3 grid size-9 place-items-center rounded-full bg-white/90 shadow-sm transition hover:bg-white"><Heart className="size-4 fill-current" /></button></div><div className="p-4"><Link href={`/product/${product.slug}`} className="font-medium hover:underline">{product.name}</Link><p className="mt-1 text-sm text-[#69717b]">{product.priceAmount === null ? 'Fiyat bilgisi yakında' : new Intl.NumberFormat(locale === 'tr' ? 'tr-TR' : 'en-US', { style: 'currency', currency: product.currency }).format(product.priceAmount)}</p></div></article>)}</div> : <div className="mt-7 rounded-2xl border border-dashed border-black/15 bg-white px-6 py-14 text-center"><Heart className="mx-auto size-7 text-[#737b85]" strokeWidth={1.4} /><h2 className="mt-4 text-lg">Favorilerin için yer hazır</h2><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-[#69717b]">Beğendiğin çerçeveleri kalp simgesine dokunarak buraya kaydedebilirsin.</p><Link href="/shop" className="mt-6 inline-flex h-10 items-center gap-2 rounded-lg bg-[#1b2635] px-4 text-sm font-medium text-white"><ShoppingBag className="size-4" /> Gözlükleri keşfet</Link></div>}</section>;
}
