import { ArrowUpRight, PackageOpen } from 'lucide-react';

function formatMoney(amount, currency, locale) { return new Intl.NumberFormat(locale === 'tr' ? 'tr-TR' : 'en-US', { style: 'currency', currency }).format(amount || 0); }
function formatDate(value, locale) { return new Intl.DateTimeFormat(locale === 'tr' ? 'tr-TR' : 'en-US', { dateStyle: 'medium' }).format(new Date(value)); }
const statusLabels = { pending: 'Hazırlanıyor', paid: 'Ödendi', cancelled: 'İptal edildi', completed: 'Tamamlandı', shipped: 'Kargoda', delivered: 'Teslim edildi' };

export default function Orders({ orders, locale }) {
  return <section><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-[#69717b]">Alışveriş geçmişin</p><h1 className="mt-1 text-[clamp(2rem,4vw,3rem)] tracking-[-0.05em]">Siparişlerim</h1></div><span className="rounded-full bg-[#f1f2ef] px-3 py-1.5 text-sm text-[#59616b]">{orders.length} kayıt</span></div>{orders.length ? <div className="mt-7 overflow-hidden rounded-2xl border border-black/10 bg-white"><div className="hidden grid-cols-[1.2fr_0.8fr_0.8fr_0.8fr_auto] gap-4 border-b border-black/8 px-5 py-3 text-xs text-[#737b85] md:grid"><span>Sipariş</span><span>Tarih</span><span>Durum</span><span>Tutar</span><span /></div>{orders.map((order) => <article key={order.orderNumber} className="grid gap-3 border-b border-black/8 px-5 py-5 last:border-0 md:grid-cols-[1.2fr_0.8fr_0.8fr_0.8fr_auto] md:items-center"><div><p className="font-medium">#{order.orderNumber}</p><p className="mt-1 text-sm text-[#727a84]">{order.itemCount} ürün</p></div><p className="text-sm text-[#59616b]">{formatDate(order.placedAt, locale)}</p><div><span className="inline-flex items-center gap-2 rounded-full bg-[#eef4f0] px-2.5 py-1 text-xs font-medium text-[#356a50]"><span className="size-1.5 rounded-full bg-[#4ca478]" />{statusLabels[order.fulfillmentStatus] || statusLabels[order.status] || order.status}</span></div><p className="font-medium tabular-nums">{formatMoney(order.totalAmount, order.currency, locale)}</p><button type="button" className="flex items-center gap-1 text-sm font-medium hover:underline">Detay <ArrowUpRight className="size-3.5" /></button></article>)}</div> : <EmptyOrders />}</section>;
}
function EmptyOrders() { return <div className="mt-7 rounded-2xl border border-dashed border-black/15 bg-white px-6 py-14 text-center"><PackageOpen className="mx-auto size-7 text-[#737b85]" strokeWidth={1.4} /><h2 className="mt-4 text-lg">Henüz siparişin yok</h2><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-[#69717b]">İlk çerçeveni keşfettiğinde sipariş durumunu burada görebileceksin.</p></div>; }
