const createImages = (folder, files) => files.map((file) => `/gozlukler/${folder}/${file}`);

const createSpecifications = (tr, en) => ({ tr, en });

const rawDemoProducts = [
  {
    code: 'CL40235U',
    slug: 'celine-paris-cl40235u-3h',
    name: 'Celine Paris CL40235U',
    brand: 'Celine Paris',
    type: 'Güneş Gözlüğü',
    price: 'Fiyat yakında',
    color: '#ffffff',
    audiences: ['unisex'],
    productType: 'sunglasses',
    material: ['metal'],
    features: ['gradient'],
    shortDescription: 'İnce metal yapısı ve oval formuyla retro çizgiyi minimal bir görünümle buluşturan güneş gözlüğü.',
    specifications: createSpecifications(
      { 'Model': 'CL40235U', 'Renk kodu': '3H', 'Ölçü': '54□18 - 145', 'Çerçeve formu': 'Oval', 'Çerçeve tipi': 'Tam çerçeve', 'Çerçeve materyali': 'Metal', 'Çerçeve rengi': 'Altın', 'Cam rengi': 'Koyu yeşil / füme yeşil', 'Sap ucu rengi': 'Siyah', 'Stil': 'İnce metal, retro, minimal' },
      { 'Model': 'CL40235U', 'Color code': '3H', 'Size': '54□18 - 145', 'Frame shape': 'Oval', 'Frame type': 'Full rim', 'Frame material': 'Metal', 'Frame color': 'Gold', 'Lens color': 'Dark green / smoke green', 'Temple tip color': 'Black', 'Style': 'Thin metal, retro, minimal' },
    ),
    images: createImages('CELINE-PARIS_CL40235U_54-18-145', ['main.webp', '1-png.png', '2-png.png', '4-png.png']),
  },
  {
    code: 'CL40254U',
    slug: 'celine-paris-cl40254u-30n',
    name: 'Celine Paris CL40254U',
    brand: 'Celine Paris',
    type: 'Güneş Gözlüğü',
    price: 'Fiyat yakında',
    color: '#ffffff',
    audiences: ['unisex'],
    productType: 'sunglasses',
    material: ['metal'],
    features: [],
    shortDescription: 'Dar geometrik formu, ince altın metal çerçevesi ve koyu yeşil camlarıyla modern bir retro görünüm.',
    specifications: createSpecifications(
      { 'Model': 'CL40254U', 'Renk kodu': '30N', 'Ölçü': '58□16 - 145', 'Lens genişliği': '58 mm', 'Köprü genişliği': '16 mm', 'Sap uzunluğu': '145 mm', 'Çerçeve rengi': 'Altın', 'Cam rengi': 'Koyu yeşil', 'Çerçeve formu': 'Dar geometrik', 'Çerçeve yapısı': 'İnce metal çerçeve', 'Sap detayı': 'Altın sap, koyu havana uç', 'Stil': 'Modern, minimal, retro' },
      { 'Model': 'CL40254U', 'Color code': '30N', 'Size': '58□16 - 145', 'Lens width': '58 mm', 'Bridge width': '16 mm', 'Temple length': '145 mm', 'Frame color': 'Gold', 'Lens color': 'Dark green', 'Frame shape': 'Narrow geometric', 'Frame construction': 'Thin metal frame', 'Temple detail': 'Gold temple, dark havana tip', 'Style': 'Modern, minimal, retro' },
    ),
    images: createImages('CELINE-PARIS_CL40254U_30N_58-16-145', ['main.webp', '1-png.png', '3-png.png', '4-png.png']),
  },
  {
    code: 'DK015',
    slug: 'diana-korr-dk015',
    name: 'Diana Korr DK015',
    brand: 'Diana Korr',
    type: 'Güneş Gözlüğü',
    price: 'Fiyat yakında',
    color: '#ffffff',
    audiences: ['unisex'],
    productType: 'sunglasses',
    material: [],
    features: ['polarized', 'gradient'],
    shortDescription: 'Beyaz geometrik cat-eye çerçevesi, mor füme degrade camları ve polarize lens yapısıyla güçlü bir siluet.',
    specifications: createSpecifications(
      { 'Model': 'DK015', 'Ölçü': '55□17 - 143', 'Lens özelliği': 'Polarize', 'UV koruması': 'UV400', 'Çerçeve rengi': 'Beyaz', 'Cam rengi': 'Mor / füme degrade', 'Form': 'Cat-eye / geometrik', 'Çerçeve tipi': 'Tam çerçeveli' },
      { 'Model': 'DK015', 'Size': '55□17 - 143', 'Lens feature': 'Polarized', 'UV protection': 'UV400', 'Frame color': 'White', 'Lens color': 'Purple / smoke gradient', 'Shape': 'Cat-eye / geometric', 'Frame type': 'Full rim' },
    ),
    images: createImages('DIANA-KORR_DK015_55-17-143', ['main.webp', '1-png.png', '2-png.png', '4-png.png']),
  },
  {
    code: 'JD2850',
    slug: 'diana-kors-jd2850',
    name: 'Diana Kors JD2850',
    brand: 'Diana Kors',
    type: 'Güneş Gözlüğü',
    price: 'Fiyat yakında',
    color: '#ffffff',
    audiences: ['unisex'],
    productType: 'sunglasses',
    material: ['metal'],
    features: [],
    shortDescription: 'Çift köprülü siyah metal yapısı ve koyu füme camlarıyla keskin, geometrik bir model.',
    specifications: createSpecifications(
      { 'Model': 'JD2850', 'Ölçü': '52□19 - 142', 'Lens genişliği': '52 mm', 'Köprü genişliği': '19 mm', 'Sap uzunluğu': '142 mm', 'Çerçeve rengi': 'Siyah', 'Cam rengi': 'Koyu füme / siyah', 'Çerçeve formu': 'Geometrik, dikdörtgen', 'Çerçeve yapısı': 'Metal, çift köprülü', 'Sap detayı': 'Siyah, kırmızı iç uç', 'Stil': 'Modern, geometrik' },
      { 'Model': 'JD2850', 'Size': '52□19 - 142', 'Lens width': '52 mm', 'Bridge width': '19 mm', 'Temple length': '142 mm', 'Frame color': 'Black', 'Lens color': 'Dark smoke / black', 'Frame shape': 'Geometric, rectangular', 'Frame construction': 'Metal, double bridge', 'Temple detail': 'Black with red inner tip', 'Style': 'Modern, geometric' },
    ),
    images: createImages('DIANA-KORS_JD2850_52-19-142', ['main.webp', '1-PNG.png', '3-PNG.png', '4-PNG.png']),
  },
  {
    code: 'FE4075US',
    slug: 'fendi-first-crystal-fe4075us-30a',
    name: 'Fendi First Crystal FE4075US',
    brand: 'Fendi',
    type: 'Güneş Gözlüğü',
    price: 'Fiyat yakında',
    color: '#ffffff',
    audiences: ['unisex'],
    productType: 'sunglasses',
    material: ['metal'],
    features: [],
    shortDescription: 'Çerçevesiz oval camları, altın metal yapısı ve kristal F logo detayıyla zarif bir Fendi modeli.',
    specifications: createSpecifications(
      { 'Model': 'Fendi First Crystal FE4075US', 'Renk kodu': '30A', 'Ölçü': '54□15 - 135', 'Çerçeve rengi': 'Altın', 'Cam rengi': 'Füme / koyu gri', 'Form': 'Oval', 'Çerçeve tipi': 'Çerçevesiz', 'Çerçeve materyali': 'Metal', 'Polarize': 'Hayır', 'Menşei': 'İtalya', 'Detay': 'Kristal F logo detayı' },
      { 'Model': 'Fendi First Crystal FE4075US', 'Color code': '30A', 'Size': '54□15 - 135', 'Frame color': 'Gold', 'Lens color': 'Smoke / dark gray', 'Shape': 'Oval', 'Frame type': 'Rimless', 'Frame material': 'Metal', 'Polarized': 'No', 'Origin': 'Italy', 'Detail': 'Crystal F logo detail' },
    ),
    images: createImages('FENDI_FE4075US_30A_54-15-135', ['main.webp', '1-PNG.png', '2-PNG.png', '4-PNG.png']),
  },
  {
    code: 'GG1604S',
    slug: 'gucci-gg1604s',
    name: 'Gucci GG1604S',
    brand: 'Gucci',
    type: 'Güneş Gözlüğü',
    price: 'Fiyat yakında',
    color: '#ffffff',
    audiences: ['unisex'],
    productType: 'sunglasses',
    material: ['metal'],
    features: [],
    shortDescription: 'Dar geometrik formu, altın metal yapısı ve Gucci GG menteşe detayıyla karakterli bir tasarım.',
    specifications: createSpecifications(
      { 'Model': 'GG1604S', 'Ölçü': '55□22 - 140', 'Cam kategorisi': 'Kategori 3', 'Çerçeve rengi': 'Altın', 'Cam rengi': 'Koyu yeşil', 'Form': 'Geometrik / dar dikdörtgen', 'Çerçeve tipi': 'Yarım çerçeveli', 'Materyal': 'Metal', 'Detay': 'Gucci GG menteşe detayı' },
      { 'Model': 'GG1604S', 'Size': '55□22 - 140', 'Lens category': 'Category 3', 'Frame color': 'Gold', 'Lens color': 'Dark green', 'Shape': 'Geometric / narrow rectangle', 'Frame type': 'Semi-rimless', 'Material': 'Metal', 'Detail': 'Gucci GG hinge detail' },
    ),
    images: createImages('GUCCI_GG1604S_55-22-140', ['main.webp', '1-PNG.png', '3-PNG.png', '4-PNG.png']),
  },
  {
    code: '2430',
    slug: 'innoxlife-2430-polarize',
    name: 'Innoxlife 2430',
    brand: 'Innoxlife',
    type: 'Güneş Gözlüğü',
    price: 'Fiyat yakında',
    color: '#ffffff',
    audiences: ['unisex'],
    productType: 'sunglasses',
    material: ['metal'],
    features: ['polarized'],
    shortDescription: 'Çift köprülü dikdörtgen metal çerçevesi ve polarize koyu füme camlarıyla günlük unisex model.',
    specifications: createSpecifications(
      { 'Model': '2430', 'Ölçü': '55□16 - 143', 'Lens genişliği': '55 mm', 'Köprü genişliği': '16 mm', 'Sap uzunluğu': '143 mm', 'Çerçeve rengi': 'Siyah', 'Cam rengi': 'Koyu füme / siyah', 'Cam özelliği': 'Polarize', 'Çerçeve materyali': 'Metal', 'Çerçeve formu': 'Dikdörtgen', 'Köprü': 'Çift köprü', 'Çerçeve yapısı': 'Tam çerçeveli', 'Kullanım': 'Unisex' },
      { 'Model': '2430', 'Size': '55□16 - 143', 'Lens width': '55 mm', 'Bridge width': '16 mm', 'Temple length': '143 mm', 'Frame color': 'Black', 'Lens color': 'Dark smoke / black', 'Lens feature': 'Polarized', 'Frame material': 'Metal', 'Frame shape': 'Rectangular', 'Bridge': 'Double bridge', 'Frame construction': 'Full rim', 'Fit': 'Unisex' },
    ),
    images: createImages('INNOXLIFE_2430_55-16-143', ['main.webp', '1-png.png', '3-png.png', '4-png.png']),
  },
  {
    code: '8125S',
    slug: 'innoxlife-8125s-clip-on',
    name: 'Innoxlife 8125S Clip-on',
    brand: 'Innoxlife',
    type: 'Optik Çerçeve',
    price: 'Fiyat yakında',
    color: '#ffffff',
    audiences: ['unisex'],
    productType: 'optical',
    material: ['metal'],
    features: ['polarized'],
    shortDescription: 'Şeffaf ana lensi ve siyah ile sarı polarize clip-on seçenekleriyle çok yönlü metal çerçeve.',
    specifications: createSpecifications(
      { 'Model': '8125S', 'Ölçü': '52□18 - 145', 'Lens genişliği': '52 mm', 'Köprü genişliği': '18 mm', 'Sap uzunluğu': '145 mm', 'Çerçeve rengi': 'Siyah', 'Çerçeve materyali': 'Metal', 'Çerçeve formu': 'Oval / geometrik', 'Ana lens': 'Şeffaf clip-on lens', 'Clip-on 01': 'Siyah / koyu füme', 'Clip-on 02': 'Sarı', 'Güneş lensleri': 'Polarize', 'Burun pedi': 'Ayarlanabilir', 'Kullanım': 'Unisex' },
      { 'Model': '8125S', 'Size': '52□18 - 145', 'Lens width': '52 mm', 'Bridge width': '18 mm', 'Temple length': '145 mm', 'Frame color': 'Black', 'Frame material': 'Metal', 'Frame shape': 'Oval / geometric', 'Main lens': 'Clear clip-on lens', 'Clip-on 01': 'Black / dark smoke', 'Clip-on 02': 'Yellow', 'Sun lenses': 'Polarized', 'Nose pads': 'Adjustable', 'Fit': 'Unisex' },
    ),
    images: createImages('INNOXLIFE_8125S_52-18-145', ['main.webp', '1-png.png', '2-png.png', '3-png.png', '4-png.png']),
  },
  {
    code: 'L6029S',
    slug: 'lacoste-l6029s-003',
    name: 'Lacoste L6029S',
    brand: 'Lacoste',
    type: 'Güneş Gözlüğü',
    price: 'Fiyat yakında',
    color: '#ffffff',
    audiences: ['unisex'],
    productType: 'sunglasses',
    material: ['acetate'],
    features: ['gradient'],
    shortDescription: 'Koyu lacivert yuvarlatılmış kare çerçevesi ve mor füme degrade camlarıyla sportif bir model.',
    specifications: createSpecifications(
      { 'Model': 'L6029S', 'Renk kodu': '003', 'Ölçü': '52□20 - 145', 'Cam kategorisi': '3N', 'Çerçeve rengi': 'Koyu lacivert', 'Cam rengi': 'Mor / füme degrade', 'Form': 'Kare / yuvarlatılmış kare', 'Çerçeve tipi': 'Tam çerçeveli', 'Materyal': 'Asetat / plastik', 'Detay': 'Lacoste timsah logosu ve yeşil-beyaz sap detayı' },
      { 'Model': 'L6029S', 'Color code': '003', 'Size': '52□20 - 145', 'Lens category': '3N', 'Frame color': 'Dark navy', 'Lens color': 'Purple / smoke gradient', 'Shape': 'Square / rounded square', 'Frame type': 'Full rim', 'Material': 'Acetate / plastic', 'Detail': 'Lacoste crocodile logo and green-white temple detail' },
    ),
    images: createImages('LACOSTE_L6029S_003_52-20-145', ['main.webp', '1-PNG.png', '3-PNG.png', '4-PNG.png']),
  },
  {
    code: '98299',
    slug: 'no-brand-98299',
    name: '98299 Oversize',
    brand: 'No Brand',
    type: 'Güneş Gözlüğü',
    price: 'Fiyat yakında',
    color: '#ffffff',
    audiences: ['unisex'],
    productType: 'sunglasses',
    material: ['metal'],
    features: ['gradient'],
    shortDescription: 'Koyu yeşil metal çerçevesi ve mavi-bej degrade camlarıyla oversize, yarım çerçeveli model.',
    specifications: createSpecifications(
      { 'Model / kod': '98299', 'Ölçü': '56□19 - 135', 'Çerçeve rengi': 'Koyu yeşil', 'Cam rengi': 'Mavi - bej degrade', 'Form': 'Oversize / yuvarlatılmış kare', 'Çerçeve tipi': 'Yarım çerçeveli', 'Çerçeve materyali': 'Metal', 'Sap ucu rengi': 'Gri' },
      { 'Model / code': '98299', 'Size': '56□19 - 135', 'Frame color': 'Dark green', 'Lens color': 'Blue - beige gradient', 'Shape': 'Oversize / rounded square', 'Frame type': 'Semi-rimless', 'Frame material': 'Metal', 'Temple tip color': 'Gray' },
    ),
    images: createImages('NO-BRAND_98299_56-19-135', ['main.webp', '1-png.png', '2-png.png', '4-png.png']),
  },
  {
    code: 'T-7040',
    slug: 'no-brand-t-7040',
    name: 'T-7040 Pilot',
    brand: 'No Brand',
    type: 'Güneş Gözlüğü',
    price: 'Fiyat yakında',
    color: '#ffffff',
    audiences: ['unisex'],
    productType: 'sunglasses',
    material: ['metal'],
    features: ['gradient'],
    shortDescription: 'Altın çift köprülü metal yapısı ve bordo-mor degrade camlarıyla geometrik pilot model.',
    specifications: createSpecifications(
      { 'Model / kod': 'T-7040', 'Ölçü': '57□15 - 142', 'Çerçeve rengi': 'Altın', 'Cam rengi': 'Bordo / mor degrade', 'Form': 'Pilot / geometrik dikdörtgen', 'Çerçeve tipi': 'Tam çerçeveli', 'Çerçeve materyali': 'Metal', 'Sap rengi': 'Turuncu / kahverengi', 'Detay': 'Çift köprü ve dekoratif metal sap' },
      { 'Model / code': 'T-7040', 'Size': '57□15 - 142', 'Frame color': 'Gold', 'Lens color': 'Burgundy / purple gradient', 'Shape': 'Pilot / geometric rectangle', 'Frame type': 'Full rim', 'Frame material': 'Metal', 'Temple color': 'Orange / brown', 'Detail': 'Double bridge and decorative metal temple' },
    ),
    images: createImages('NO-BRAND_T-7040_57-15-142', ['main.webp', '2-png.png', '3-png.png', '4-png.png']),
  },
  {
    code: 'PR17WS',
    slug: 'prada-pr17ws-1ab5s0',
    name: 'Prada PR 17WS',
    brand: 'Prada Milano',
    type: 'Güneş Gözlüğü',
    price: 'Fiyat yakında',
    color: '#ffffff',
    audiences: ['unisex'],
    productType: 'sunglasses',
    material: ['acetate'],
    features: [],
    shortDescription: 'Siyah asetat çerçevesi ve koyu gri camlarıyla köşeli, dikdörtgen Prada modeli.',
    specifications: createSpecifications(
      { 'Model': 'PR 17WS', 'Renk kodu': '1AB5S0', 'Çerçeve rengi': 'Siyah', 'Çerçeve materyali': 'Asetat', 'Cam rengi': 'Koyu gri', 'Çerçeve formu': 'Köşeli / dikdörtgen', 'Cam genişliği': '49 mm', 'Köprü genişliği': '21 mm', 'Sap uzunluğu': '145 mm', 'Cam kategorisi': '4N' },
      { 'Model': 'PR 17WS', 'Color code': '1AB5S0', 'Frame color': 'Black', 'Frame material': 'Acetate', 'Lens color': 'Dark gray', 'Frame shape': 'Angular / rectangular', 'Lens width': '49 mm', 'Bridge width': '21 mm', 'Temple length': '145 mm', 'Lens category': '4N' },
    ),
    images: createImages('PRADA_PR17WS_1AB5S0', ['main.webp', '1.png', '3.png', '4.png']),
  },
  {
    code: 'SPR58Y',
    slug: 'prada-spr58y-2vn-5y1',
    name: 'Prada SPR 58Y',
    brand: 'Prada',
    type: 'Güneş Gözlüğü',
    price: 'Fiyat yakında',
    color: '#ffffff',
    audiences: ['unisex'],
    productType: 'sunglasses',
    material: ['metal'],
    features: [],
    shortDescription: 'Altın metal gövdesi, kahverengi camları ve havana saplarıyla geometrik pilot form.',
    specifications: createSpecifications(
      { 'Model': 'SPR 58Y', 'Renk kodu': '2VN-5Y1', 'Ölçü': '57□15 - 145', 'Cam kategorisi': '3N', 'Çerçeve rengi': 'Altın', 'Cam rengi': 'Kahverengi', 'Sap rengi': 'Havana / kaplumbağa deseni', 'Form': 'Pilot / geometrik dikdörtgen', 'Çerçeve tipi': 'Tam çerçeveli', 'Materyal': 'Metal', 'Detay': 'Çift köprü ve Prada logo plakası', 'UV koruması': '%100 UV koruma' },
      { 'Model': 'SPR 58Y', 'Color code': '2VN-5Y1', 'Size': '57□15 - 145', 'Lens category': '3N', 'Frame color': 'Gold', 'Lens color': 'Brown', 'Temple color': 'Havana / tortoise', 'Shape': 'Pilot / geometric rectangle', 'Frame type': 'Full rim', 'Material': 'Metal', 'Detail': 'Double bridge and Prada logo plaque', 'UV protection': '100% UV protection' },
    ),
    images: createImages('PRADA_SPR58Y_2VN-5Y1_57-15-145', ['main.webp', '1-PNG.png', '2-PNG.png', '4-PNG.png']),
  },
  {
    code: 'RB2140-901',
    slug: 'ray-ban-rb2140-wayfarer-901',
    name: 'Ray-Ban RB2140 Wayfarer',
    brand: 'Ray-Ban',
    type: 'Güneş Gözlüğü',
    price: 'Fiyat yakında',
    color: '#ffffff',
    audiences: ['unisex'],
    productType: 'sunglasses',
    material: ['acetate'],
    features: [],
    shortDescription: 'Siyah asetat Wayfarer çerçevesi ve koyu yeşil camlarıyla zamansız Ray-Ban modeli.',
    specifications: createSpecifications(
      { 'Model / kod': 'RB2140 Wayfarer', 'Renk kodu': '901', 'Ölçü': '50□22 - 150', 'Filtre kodu': '3N', 'Çerçeve rengi': 'Siyah', 'Cam rengi': 'Koyu yeşil / çok koyu gri-yeşil', 'Form': 'Wayfarer', 'Çerçeve tipi': 'Tam çerçeveli', 'Materyal': 'Asetat', 'Sap rengi': 'Siyah' },
      { 'Model / code': 'RB2140 Wayfarer', 'Color code': '901', 'Size': '50□22 - 150', 'Filter code': '3N', 'Frame color': 'Black', 'Lens color': 'Dark green / very dark gray-green', 'Shape': 'Wayfarer', 'Frame type': 'Full rim', 'Material': 'Acetate', 'Temple color': 'Black' },
    ),
    images: createImages('RAY-BAN_RB2140-901_50-22-150', ['main.webp', '1-PNG.png', '3-PNG.png', '4-PNG.png']),
  },
  {
    code: 'RB3460M',
    slug: 'ray-ban-scuderia-ferrari-rb3460m-f008-13',
    name: 'Ray-Ban Scuderia Ferrari RB3460M',
    brand: 'Ray-Ban',
    type: 'Güneş Gözlüğü',
    price: 'Fiyat yakında',
    color: '#ffffff',
    audiences: ['unisex'],
    productType: 'sunglasses',
    material: ['mixed'],
    features: ['gradient'],
    shortDescription: 'Scuderia Ferrari detayları, altın pilot çerçevesi ve karbon görünümlü saplarıyla sportif model.',
    specifications: createSpecifications(
      { 'Koleksiyon': 'Scuderia Ferrari Collection', 'Model': 'RB3460M', 'Renk kodu': 'F008/13', 'Ölçü': '59□13 - 140', 'Cam kategorisi': '3N', 'Çerçeve rengi': 'Altın', 'Cam rengi': 'Kahverengi / bordo degrade', 'Form': 'Pilot / aviator', 'Çerçeve tipi': 'Tam çerçeveli', 'Materyal': 'Metal + karbon', 'Sap rengi': 'Koyu gri / karbon görünümlü', 'Detay': 'Scuderia Ferrari logosu ve koleksiyon detayları' },
      { 'Collection': 'Scuderia Ferrari Collection', 'Model': 'RB3460M', 'Color code': 'F008/13', 'Size': '59□13 - 140', 'Lens category': '3N', 'Frame color': 'Gold', 'Lens color': 'Brown / burgundy gradient', 'Shape': 'Pilot / aviator', 'Frame type': 'Full rim', 'Material': 'Metal + carbon', 'Temple color': 'Dark gray / carbon look', 'Detail': 'Scuderia Ferrari logo and collection details' },
    ),
    images: createImages('RAY-BAN_RB3460M_F008-13_59-13-140', ['main.webp', '1-PNG.png', '3-PNG.png', '4-PNG.png']),
  },
  {
    code: 'RB3016',
    slug: 'ray-ban-rb3016-clubmaster-902-57',
    name: 'Ray-Ban RB3016 Clubmaster',
    brand: 'Ray-Ban',
    type: 'Güneş Gözlüğü',
    price: 'Fiyat yakında',
    color: '#ffffff',
    audiences: ['unisex'],
    productType: 'sunglasses',
    material: ['mixed'],
    features: [],
    shortDescription: 'Havana asetat ve altın metal birleşimiyle ikonik Clubmaster browline formu.',
    specifications: createSpecifications(
      { 'Model': 'RB3016 Clubmaster', 'Renk kodu': '902/57', 'Ölçü': '51□21 - 145', 'Cam kategorisi': '3N', 'Çerçeve rengi': 'Havana / kaplumbağa deseni + altın', 'Cam rengi': 'Kahverengi', 'Form': 'Clubmaster / browline', 'Çerçeve tipi': 'Yarım çerçeveli', 'Materyal': 'Asetat + metal' },
      { 'Model': 'RB3016 Clubmaster', 'Color code': '902/57', 'Size': '51□21 - 145', 'Lens category': '3N', 'Frame color': 'Havana / tortoise + gold', 'Lens color': 'Brown', 'Shape': 'Clubmaster / browline', 'Frame type': 'Semi-rimless', 'Material': 'Acetate + metal' },
    ),
    images: createImages('RAYBAN_RB3016_CLUBMASTER_902-57', ['main.webp', '1-PNG.png', '3-PNG.png', '4-PNG.png']),
  },
  {
    code: 'RB3674M',
    slug: 'ray-ban-scuderia-ferrari-rb3674m-f002-6g',
    name: 'Ray-Ban Scuderia Ferrari RB3674M',
    brand: 'Ray-Ban',
    type: 'Güneş Gözlüğü',
    price: 'Fiyat yakında',
    color: '#ffffff',
    audiences: ['unisex'],
    productType: 'sunglasses',
    material: ['mixed'],
    features: [],
    shortDescription: 'Kırmızı-siyah çerçevesi ve Ferrari koleksiyon detaylarıyla yuvarlatılmış geometrik model.',
    specifications: createSpecifications(
      { 'Koleksiyon': 'Scuderia Ferrari', 'Model': 'RB3674-M', 'Renk kodu': 'F002/6G', 'Ölçü': '51□21 - 145', 'Cam kategorisi': '3N', 'Çerçeve rengi': 'Kırmızı / siyah', 'Cam rengi': 'Koyu füme', 'Form': 'Yuvarlatılmış geometrik / oval', 'Materyal': 'Metal çerçeve + plastik sap' },
      { 'Collection': 'Scuderia Ferrari', 'Model': 'RB3674-M', 'Color code': 'F002/6G', 'Size': '51□21 - 145', 'Lens category': '3N', 'Frame color': 'Red / black', 'Lens color': 'Dark smoke', 'Shape': 'Rounded geometric / oval', 'Material': 'Metal frame + plastic temples' },
    ),
    images: createImages('RAYBAN_SCUDERIA-FERRARI_RB3674M_F002-6G', ['main.webp', '1.png', '3.png', '4.png']),
  },
  {
    code: 'VE2287',
    slug: 'versace-ve2287',
    name: 'Versace VE2287',
    brand: 'Versace',
    type: 'Güneş Gözlüğü',
    color: '#ffffff',
    audiences: ['unisex'],
    productType: 'sunglasses',
    material: ['metal'],
    features: [],
    shortDescription: 'Keskin geometrik formu ve metal çerçevesiyle güçlü bir Versace güneş gözlüğü.',
    specifications: createSpecifications(
      { Model: 'VE2287', 'Ürün tipi': 'Güneş gözlüğü', Materyal: 'Metal' },
      { Model: 'VE2287', 'Product type': 'Sunglasses', Material: 'Metal' },
    ),
    images: ['/demo-gozlukler/versace-ve2287/main.webp', '/demo-gozlukler/versace-ve2287/1.webp', '/demo-gozlukler/versace-ve2287/2.webp'],
  },
  {
    code: 'IP-VND268',
    slug: 'inesta-polarized-ip-vnd268',
    name: 'Inesta Polarized IP VND268',
    brand: 'Inesta',
    type: 'Güneş Gözlüğü',
    color: '#ffffff',
    audiences: ['unisex'],
    productType: 'sunglasses',
    material: ['acetate'],
    features: ['polarized'],
    shortDescription: 'Şeffaf kahve çerçevesi ve polarize füme camlarıyla günlük kullanıma uygun model.',
    specifications: createSpecifications(
      { Model: 'IP VND268', Ölçü: '53□18', 'Lens özelliği': 'Polarize', 'Çerçeve rengi': 'Şeffaf kahve' },
      { Model: 'IP VND268', Size: '53□18', 'Lens feature': 'Polarized', 'Frame color': 'Transparent brown' },
    ),
    images: ['/demo-gozlukler/inesta-polarized-ip-vnd268/main.webp', '/demo-gozlukler/inesta-polarized-ip-vnd268/1.webp', '/demo-gozlukler/inesta-polarized-ip-vnd268/2.webp'],
  },
];

const prices = [
  18990, 19990, 2490, 2790, 22990, 24990, 3290, 4490, 8990, 1990,
  2290, 16990, 17990, 6490, 9490, 8290, 8990, 12990, 3790,
];

const demoProducts = rawDemoProducts.map((product, index) => {
  const extraImages = product.code === 'RB2140-901'
    ? ['/demo-gozlukler/rayban-rb2140-wayfarer-50mm/main.webp', '/demo-gozlukler/rayban-rb2140-wayfarer-50mm/1.webp', '/demo-gozlukler/rayban-rb2140-wayfarer-50mm/2.webp']
    : product.code === '8125S'
      ? ['/demo-gozlukler/INNOXLIFE_8125S_52-18-145/1-png.png', '/demo-gozlukler/INNOXLIFE_8125S_52-18-145/2-png.png']
      : [];
  const price = prices[index];
  return {
    ...product,
    price,
    compareAtPrice: index % 3 === 0 ? Math.round(price * 1.12 / 10) * 10 : null,
    stockQuantity: 12 + (index % 7),
    images: [...product.images, ...extraImages],
  };
});

module.exports = { demoProducts };
